apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube-bench-server
    version: v1
  name: kube-bench-server
  namespace: hokun
spec:
  containers:
  - args:
    - -c
    - python3 /home/server.py
    command:
    - /bin/sh
    image: docker.io/hokunpark/bench:imageDownloadServer
    imagePullPolicy: Always
    name: server
    resources:
      limits:
        cpu: 3
        memory: 1000Mi
      requests:
        cpu: 3
        memory: 1000Mi
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: /home/dnclab/hokun/kube
      name: kube-bench-server-vol
  volumes:
  - emptyDir:
      sizeLimit: 5Gi
    name: kube-bench-server-vol
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube-bench-client1
    version: v1
  name: kube-bench-client1
  namespace: hokun
spec:
  containers:
  - args:
    - -c
    - sleep 36000
    command:
    - /bin/sh
    image: docker.io/hokunpark/bench:imageDownloadClient
    imagePullPolicy: Always
    name: client
    resources:
      limits:
        cpu: 3
        memory: 1000Mi
      requests:
        cpu: 3
        memory: 1000Mi
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: /home/dnclab/hokun/kube
      name: kube-bench-client-vol
  volumes:
  - emptyDir:
      sizeLimit: 5Gi
    name: kube-bench-client-vol
---
apiVersion: v1
kind: Service
metadata:
  name: kube-bench-server-service
  namespace: hokun
spec:
  ports:
  - port: 15015
    protocol: TCP
    targetPort: 15015
  selector:
    app: kube-bench-server
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kube-bench-server-dr
  namespace: hokun
spec:
  host: kube-bench-server-service
  subsets:
  - labels:
      version: v1
    name: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kube-bench-server-vs
  namespace: hokun
spec:
  hosts:
  - kube-bench-server-service
  http:
  - route:
    - destination:
        host: kube-bench-server-service
        subset: v1
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: envoy-access-logs-server
  namespace: hokun
spec:
  accessLogging:
  - providers:
    - name: enable-targeted-envoy-access-logs
  selector:
    matchLabels:
      app: kube-bench-server
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: envoy-access-logs-client
  namespace: hokun
spec:
  accessLogging:
  - providers:
    - name: enable-targeted-envoy-access-logs
  selector:
    matchLabels:
      app: kube-bench-client1
