apiVersion: v1
kind: Pod 
metadata:
  name: kube-bench-server
  namespace: hokun
  labels:
    app: kube-bench-server   
    version: v1

spec:         
  containers:
  - name: server
    image: "docker.io/hokunpark/kube:benchserver"             
    imagePullPolicy: Always
    resources:
     requests:
       cpu: 2
       memory: 2Gi
     limits:
       cpu: 2
       memory: 2Gi
    securityContext:
      runAsUser: 0     
    command: ["/bin/sh"] 
    args: ["-c", "python3 /home/server.py"]


    volumeMounts:
        - name: kube-bench-server-vol
          mountPath: /home/dnclab/hokun/kube

  volumes:
    - name: kube-bench-server-vol
      emptyDir:
        sizeLimit: 5Gi
---
apiVersion: v1
kind: Pod 
metadata:
  name: kube-bench-client1
  namespace: hokun
  labels:
    app: kube-bench-client1  
    version: v1 
spec:         
  containers:
  - name: client
    image: "docker.io/hokunpark/kube:benchclient"             
    imagePullPolicy: Always
    resources:
     requests:
       cpu: 2
       memory: 2Gi
     limits:
       cpu: 2
       memory: 2Gi
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "sleep 36000"]

    volumeMounts:
        - name: kube-bench-client-vol
          mountPath: /home/dnclab/hokun/kube

  volumes:
    - name: kube-bench-client-vol
      emptyDir:
        sizeLimit: 5Gi  
     
---
apiVersion: v1
kind: Pod 
metadata:
  name: kube-bench-client2
  namespace: hokun
  labels:
    app: kube-bench-client2
    version: v1 
spec:         
  containers:
  - name: client
    image: "docker.io/hokunpark/kube:benchclient"             
    imagePullPolicy: Always
    resources:
     requests:
       cpu: 2
       memory: 2Gi
     limits:
       cpu: 2
       memory: 2Gi
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "sleep 36000"]

    volumeMounts:
        - name: kube-bench-client-vol
          mountPath: /home/dnclab/hokun/kube

  volumes:
    - name: kube-bench-client-vol
      emptyDir:
        sizeLimit: 5Gi  

---
apiVersion: v1
kind: Pod 
metadata:
  name: kube-bench-client3
  namespace: hokun
  labels:
    app: kube-bench-client3   
    version: v1 
spec:         
  containers:
  - name: client
    image: "docker.io/hokunpark/kube:benchclient"             
    imagePullPolicy: Always
    resources:
     requests:
       cpu: 2
       memory: 2Gi
     limits:
       cpu: 2
       memory: 2Gi
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "sleep 36000"]

    volumeMounts:
        - name: kube-bench-client-vol
          mountPath: /home/dnclab/hokun/kube

  volumes:
    - name: kube-bench-client-vol
      emptyDir:
        sizeLimit: 5Gi  

---
apiVersion: v1
kind: Pod 
metadata:
  name: kube-bench-client4
  namespace: hokun
  labels:
    app: kube-bench-client4 
    version: v1 
spec:         
  containers:
  - name: client
    image: "docker.io/hokunpark/kube:benchclient"             
    imagePullPolicy: Always
    resources:
     requests:
       cpu: 2
       memory: 2Gi
     limits:
       cpu: 2
       memory: 2Gi
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "sleep 36000"]

    volumeMounts:
        - name: kube-bench-client-vol
          mountPath: /home/dnclab/hokun/kube

  volumes:
    - name: kube-bench-client-vol
      emptyDir:
        sizeLimit: 5Gi  

---
apiVersion: v1
kind: Pod 
metadata:
  name: kube-bench-client5
  namespace: hokun
  labels:
    app: kube-bench-client5  
    version: v1 
spec:         
  containers:
  - name: client
    image: "docker.io/hokunpark/kube:benchclient"             
    imagePullPolicy: Always
    resources:
     requests:
       cpu: 2
       memory: 2Gi
     limits:
       cpu: 2
       memory: 2Gi
    securityContext:
      runAsUser: 0
    command: ["/bin/sh"]
    args: ["-c", "sleep 36000"]

    volumeMounts:
        - name: kube-bench-client-vol
          mountPath: /home/dnclab/hokun/kube

  volumes:
    - name: kube-bench-client-vol
      emptyDir:
        sizeLimit: 5Gi    

---
apiVersion: v1
kind: Service
metadata:
  name: kube-bench-server-service
  namespace: hokun
spec:
  selector:
    app: kube-bench-server
  ports:
    - protocol: TCP
      port: 15015
      targetPort: 15015

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kube-bench-server-dr
  namespace: hokun
spec:
  host: kube-bench-server-service
  subsets:
  - name: v1
    labels:
      version: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kube-bench-server-vs
  namespace: hokun
spec:
  hosts:
  - kube-bench-server-service
  http:
  - route:
    - destination:
        host: kube-bench-server-service
        subset: v1
        
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: envoy-access-logs-server
  namespace: hokun # Pod's namespace
spec:
  selector:
    matchLabels:
      app: kube-bench-server  # Pod's label
  accessLogging:
  - providers:
    - name: enable-targeted-envoy-access-logs

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: envoy-access-logs-client
  namespace: hokun # Pod's namespace
spec:
  selector:
    matchLabels:
      app: kube-bench-client1 
      app: kube-bench-client2
      app: kube-bench-client3
      app: kube-bench-client4
      app: kube-bench-client5 # Pod's label
  accessLogging:
  - providers:
    - name: enable-targeted-envoy-access-logs
