apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube-bench-server
    version: v1
  name: kube-bench-server
  namespace: cherry
spec:
  containers:
  - args:
    - -c
    - python3 /home/server.py
    command:
    - /bin/sh
    image: docker.io/hokunpark/bench:imageDownloadServer
    imagePullPolicy: Always
    name: server
    resources:
      limits:
        cpu: 3
        memory: 1Gi
      requests:
        cpu: 3
        memory: 1Gi
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: /home/dnclab/hokun/kube
      name: kube-bench-server-vol
  nodeSelector:
    key: worker1
  volumes:
  - emptyDir:
      sizeLimit: 5Gi
    name: kube-bench-server-vol
