apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube-bench-client1
    version: v1
  name: kube-bench-client1
  namespace: apple
spec:
  containers:
  - args:
    - -c
    - sleep 36000
    command:
    - /bin/sh
    image: docker.io/hokunpark/bench:imageDownloadClient
    imagePullPolicy: Always
    name: client
    resources:
      limits:
        cpu: 3
        memory: 1000Mi
      requests:
        cpu: 3
        memory: 1000Mi
    securityContext:
      runAsUser: 0
    volumeMounts:
    - mountPath: /home/dnclab/hokun/kube
      name: kube-bench-client-vol
  nodeSelector:
    key: worker2
  volumes:
  - emptyDir:
      sizeLimit: 5Gi
    name: kube-bench-client-vol
