apiVersion: v1
kind: PersistentVolume
metadata:
  name: hokun-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /home/dnclab/hokun/kube/saveData