apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hokun-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual